web:
  image: richarvey/nginx-php-fpm
  ports:
    - "80:80"
  links:
    - db:DB
  volumes:
    - /root/wordpress/wwwroot/:/home
    - /root/wordpress/nginx-sites:/etc/nginx/sites-enabled
db:
  image: mysql/mysql-server:5.6
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes:
   - /root/wordpress/mysql-data:/var/lib/mysql
